# Generated by Django 5.2 on 2025-04-24 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the fitness goal (e.g. weight loss, muscle gain)",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or guidance for the goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="Telegram chat ID (used for sending notifications)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full name or nickname", max_length=100),
                ),
                ("age", models.PositiveIntegerField(help_text="User's age in years")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1, help_text="Weight in kg", max_digits=5
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=1, help_text="Height in cm", max_digits=5
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        help_text="Gender of the user",
                        max_length=10,
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(
                        blank=True,
                        help_text="Medical limitations or injuries (free text)",
                    ),
                ),
                (
                    "training_location",
                    models.CharField(
                        choices=[
                            ("gym", "Gym"),
                            ("home", "Home"),
                            ("outdoors", "Outdoors"),
                        ],
                        help_text="Preferred training location",
                        max_length=50,
                    ),
                ),
                (
                    "available_days",
                    models.JSONField(
                        default=list,
                        help_text="List of days user is available for training (e.g. ['mon', 'wed', 'fri'])",
                    ),
                ),
                (
                    "preferred_time",
                    models.TimeField(help_text="Preferred daily training time"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date of registration",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        help_text="Main fitness goal selected by the user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["telegram_id"], name="profiles_cl_telegra_b5ed9d_idx"
                    )
                ],
            },
        ),
    ]
