# Generated by Django 4.2.20 on 2025-04-24 11:20

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the workout session", max_length=100
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("stretching", "Stretching"),
                            ("yoga", "Yoga"),
                            ("mixed", "Mixed"),
                        ],
                        help_text="Main type of the workout: strength, cardio, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Short summary of the workout session"),
                ),
                (
                    "duration_est",
                    models.PositiveIntegerField(
                        help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="Recommended experience level for this workout",
                        max_length=20,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="If unchecked, this workout is archived"
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Goal this workout targets (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
                "ordering": ["name"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sets",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of sets (for strength exercises)",
                        null=True,
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of reps per set (for strength exercises)",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in seconds (for cardio/stretching exercises)",
                        null=True,
                    ),
                ),
                (
                    "rest_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rest time in seconds after this exercise",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Execution order within the workout"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes or tips for this exercise"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        help_text="Reference to the base exercise",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        help_text="Workout session this exercise belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Exercise",
                "verbose_name_plural": "Workout Exercises",
                "ordering": ["workout", "order"],
            },
        ),
    ]
