# Generated by Django 4.2.20 on 2025-04-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="category",
            field=models.CharField(
                choices=[
                    ("strength", "Сила"),
                    ("cardio", "Кардио"),
                    ("stretching", "Растяжка"),
                    ("yoga", "Йога"),
                    ("mixed", "Смешанное"),
                ],
                help_text="Main type of the workout: strength, cardio, etc.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Новичок"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                help_text="Recommended experience level for this workout",
                max_length=20,
            ),
        ),
    ]
