# Generated by Django 5.2 on 2025-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the exercise", max_length=100),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("stretching", "Stretching"),
                            ("yoga", "Yoga"),
                            ("mixed", "Mixed"),
                        ],
                        help_text="Main type: strength, cardio, yoga, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("shoulders", "Shoulders"),
                            ("arms", "Arms"),
                            ("legs", "Legs"),
                            ("core", "Core"),
                            ("full_body", "Full Body"),
                            ("cardio", "Cardiovascular System"),
                            ("flexibility", "Flexibility / Mobility"),
                            ("other", "Other"),
                        ],
                        help_text="Primary muscle group targeted",
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("bodyweight", "Bodyweight"),
                            ("dumbbells", "Dumbbells"),
                            ("barbell", "Barbell"),
                            ("resistance_bands", "Resistance Bands"),
                            ("kettlebell", "Kettlebell"),
                            ("machine", "Machine"),
                            ("mat", "Mat"),
                            ("bench", "Bench"),
                            ("none", "No Equipment"),
                            ("other", "Other"),
                        ],
                        help_text="Required equipment for the exercise",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="Recommended difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Instructions and notes about execution"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True, help_text="Link to a demo video or image (optional)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["type"], name="exercises_e_type_6d7c1f_idx"),
                    models.Index(
                        fields=["muscle_group"], name="exercises_e_muscle__0d495e_idx"
                    ),
                ],
            },
        ),
    ]
