# Generated by Django 4.2.20 on 2025-04-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="media_file",
            field=models.FileField(blank=True, null=True, upload_to="exercises/"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Новичок"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                help_text="Recommended difficulty level",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="equipment",
            field=models.CharField(
                choices=[
                    ("bodyweight", "Собственный вес"),
                    ("dumbbells", "Гантели"),
                    ("barbell", "Штанга"),
                    ("resistance_bands", "Эспандеры / Резиновые ленты"),
                    ("kettlebell", "Гиря"),
                    ("machine", "Тренажёры"),
                    ("bench", "Скамья"),
                    ("cable", "Блочный тренажёр"),
                    ("medicine_ball", "Медицинский мяч"),
                    ("stability_ball", "Фитбол"),
                    ("bosu_ball", "Босу-платформа"),
                    ("foam_roller", "Массажный ролик (Foam Roller)"),
                    ("box", "Плиометрическая тумба"),
                    ("pull_up_bar", "Турник"),
                    ("rope", "Канат"),
                    ("trx", "TRX-петли"),
                    ("smith_machine", "Силовая рама (Смит-машина)"),
                    ("mat", "Коврик"),
                    ("other", "Другое"),
                ],
                help_text="Required equipment for the exercise",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("chest", "Грудные мышцы"),
                    ("back", "Спина"),
                    ("shoulders", "Плечи"),
                    ("arms", "Руки"),
                    ("legs", "Ноги"),
                    ("core", "Пресс / Корпус"),
                    ("full_body", "Всё тело"),
                    ("flexibility", "Гибкость / Подвижность"),
                    ("other", "Другое"),
                ],
                help_text="Primary muscle group targeted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                choices=[
                    ("strength", "Сила"),
                    ("cardio", "Кардио"),
                    ("stretching", "Растяжка"),
                    ("yoga", "Йога"),
                    ("mixed", "Смешанное"),
                ],
                help_text="Main type: strength, cardio, yoga, etc.",
                max_length=20,
            ),
        ),
    ]
