# Generated by Django 4.2.20 on 2025-04-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_exercise_media_file_alter_exercise_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"verbose_name": "Exercise", "verbose_name_plural": "Exercises"},
        ),
    ]
