# Generated by Django 4.2.20 on 2025-04-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Новичок"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                ],
                help_text="Difficulty level (e.g., beginner, intermediate, advanced)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="location_type",
            field=models.CharField(
                choices=[("gym", "Зал"), ("home", "Дом"), ("outdoors", "Улица")],
                help_text="Preferred training location (e.g., gym, home, any)",
                max_length=20,
            ),
        ),
    ]
