# Generated by Django 4.2.20 on 2025-04-24 11:22

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
        ("profiles", "0001_initial"),
        ("programs", "0001_initial"),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateField(help_text="Start date of the plan")),
                ("end_date", models.DateField(help_text="End date of the plan")),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="Plan status: active, completed, or cancelled",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveIntegerField(
                        default=0, help_text="Completion progress in percentage"
                    ),
                ),
                (
                    "client_profile",
                    models.ForeignKey(
                        help_text="Profile assigned to this training plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.clientprofile",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        help_text="Goal at the time of plan generation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.goal",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Base program used for generating the plan (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Plan",
                "verbose_name_plural": "Training Plans",
                "ordering": ["-start_date"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(help_text="Date of progress record")),
                (
                    "metric",
                    models.CharField(
                        help_text="Type of metric: weight, reps, time, bodyfat, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, help_text="Value of the metric", max_digits=10
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        help_text="Units of the metric (e.g. kg, %, min, reps)",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional info or context"
                    ),
                ),
                (
                    "client_profile",
                    models.ForeignKey(
                        help_text="User this progress entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.clientprofile",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific exercise this metric is for (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exercises.exercise",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related training plan (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plans.plan",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workout this progress is related to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress Record",
                "verbose_name_plural": "Progress Records",
                "ordering": ["-date"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(help_text="Scheduled date of the workout")),
                ("time", models.TimeField(help_text="Scheduled time for the workout")),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Sequential number of workout in the plan"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Was the workout completed?"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when workout was completed",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional user notes or feedback"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Training plan this schedule entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        help_text="Workout session assigned to this date",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Entry",
                "verbose_name_plural": "Schedule",
                "ordering": ["date", "time"],
                "unique_together": {("plan", "date")},
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
