# Generated by Django 4.2.20 on 2025-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активный"),
                    ("completed", "Выполнен"),
                    ("cancelled", "Отменен"),
                ],
                default="active",
                help_text="Plan status: active, completed, or cancelled",
                max_length=20,
            ),
        ),
    ]
